SELECT * FROM USUARIO
GO

SELECT
	U.ID AS 'IDUSUARIO',
	U.NOME AS 'NOMEUSUARIO',
	U.EMAIL AS 'EMAILUSUARIO',
	U.SENHA AS 'SENHAUSUARIO',
	U.DATAHORACADASTRO AS 'DATAHORACADASTRO',
	P.ID AS 'IDPERFIL',
	P.NOME AS 'NOMEPERFIL'
FROM USUARIO U
INNER JOIN PERFIL P
ON P.ID = U.PERFIL_ID